### ISSUE TITLE
Add CI lint for proto files and `protoc` compiler installation to rust CI

### ISSUE THREAD

**Issue by Velnbur** [alpenlabs/strata-p2p#5]
### Describe the feature

We have something like this right now:

```yaml
name: Protobuf

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Apply to all pull requests
jobs:
  lint-protos:
    name: lint
    runs-on: ubuntu-latest
    # Run `git checkout`
    steps:
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses:
          bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
```

With this `buf` configuration file in root called `buf.yaml`:

```yaml
version: v2
modules:
  - path: proto
lint:
  use:
    - STANDARD
  except:
    - PACKAGE_VERSION_SUFFIX
    - ENUM_VALUE_PREFIX
```

Also, in each step for `protoc` installation, we added this step to all Rust jobs:

```yaml
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
```
